#!/usr/bin/env python3.10

import argparse
import ast
from io import IOBase

from xdsl.ir import MLContext
from xdsl.dialects.builtin import ModuleOp

from tiny_py_to_standard import tiny_py_to_standard

from tiny_py import tinyPyIR
from util.semantic_error import SemanticError

from typing import Callable, Dict, List

from xdsl.xdsl_opt_main import xDSLOptMain

class PsyOptMain(xDSLOptMain):

    passes_native = [       
      tiny_py_to_standard
    ]

    def register_all_passes(self):
        self.available_passes = self.get_passes_as_dict()

    def _output_fortran(prog: ModuleOp, output: IOBase):
        print_fortran(prog.ops, stream=output)

    def register_all_targets(self):
        super().register_all_targets()        

    def setup_pipeline(self):        
      super().setup_pipeline()        

    def register_all_dialects(self):
        super().register_all_dialects()
        """Register all dialects that can be used."""        
        tinypy_ir = tinyPyIR(self.ctx)                

    @staticmethod
    def get_passes_as_dict(
    ) -> Dict[str, Callable[[MLContext, ModuleOp], None]]:
        """Add all passes that can be called by psy-opt in a dictionary."""

        pass_dictionary = {}

        passes = PsyOptMain.passes_native

        for pass_function in passes:
            pass_dictionary[pass_function.__name__.replace(
                "_", "-")] = pass_function

        return pass_dictionary

    def get_passes_as_list(native=False, integrated=False) -> List[str]:
        """Add all passes that can be called by psy-opt in a dictionary."""

        pass_list = []
        
        passes = PsyOptMain.passes_native
        
        for pass_function in passes:
            pass_list.append(pass_function.__name__.replace("_", "-"))

        return pass_list

    def register_all_frontends(self):
        super().register_all_frontends()        

def __main__():
    psy_main = PsyOptMain()

    try:
        module = psy_main.parse_input()
        psy_main.apply_passes(module)
    except SyntaxError as e:
        print(e.get_message())
        exit(0)
    except SemanticError as e:
        print("Semantic error: %s" % str(e))
        exit(0)

    contents = psy_main.output_resulting_program(module)
    psy_main.print_to_output_stream(contents)


if __name__ == "__main__":
    __main__()
